# Generated by Django 3.2.20 on 2024-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(choices=[('current', 'Current'), ('minutely', 'Minute'), ('hourly', 'Hour'), ('daily', 'Daily')], max_length=8)),
                ('time_requested', models.DateField(auto_now_add=True)),
                ('weather_data', models.JSONField()),
            ],
        ),
    ]
