# Generated by Django 3.2.20 on 2024-01-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='time_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
